### PR TITLE
bump peer dependency for angular 14

### PR DESCRIPTION
**Pull request by sthompson-celerity**
Everything looks fine on angular 14, I am running it locally

### CODE REVIEW

**Comment by acerix** [comment]
https://github.com/fullcalendar/fullcalendar-angular/issues/404

**Comment by maertz** [comment]
Bump on this

**Comment by joelcoxokc** [comment]
Bump on this?

**Comment by mpab1410** [comment]
@arshaw Any updates on this? This is keeping our team from fully moving to Angular 14

**Comment by joelcoxokc** [comment]
> @arshaw Any updates on this? This is keeping our team from fully moving to Angular 14

We had to fork and reference a github repo link in our npm package... 

Until full calendar just clicks merge

**Comment by sixpeteunder** [comment]
@joelcoxokc is everything working? Also, could you please link to that fork?

**Comment by joelcoxokc** [comment]
@sixpeteunder Im not able to link it, because its an internal repo at our company. 

But everything worked just fine. 

Doesnt seem like @arshaw or the other developers are maintaining the full calendar project any more. 
The only merged PR in the last 2 years was to "say they support angular 13"

Our team is no longer going to be using full calendar because it lacks appropriate support.

**Comment by ocell** [comment]
Hello, I am stuck also for angular 14 upgrade... do you know any other alternative to full calendar for angular? Did you fork it with v14 change to another public rpm?

Thank you!

**Comment by GlennRBS** [comment]
> @sixpeteunder Im not able to link it, because its an internal repo at our company.
> 
> But everything worked just fine.
> 
> Doesnt seem like @arshaw or the other developers are maintaining the full calendar project any more. The only merged PR in the last 2 years was to "say they support angular 13"
> 
> Our team is no longer going to be using full calendar because it lacks appropriate support.

Just curious, what are you replacing fullcalendar with?

**Comment by arshaw** [comment]
v6 now supports 12 - 15
https://github.com/fullcalendar/fullcalendar-angular/blob/v6.0.0/lib/package.json#L23

**Pull request closed without merging**
