### PR TITLE
Angular11

### PR DESCRIPTION
**Pull request by irustm**

### CODE REVIEW

**Comment by riccardomessineo** [comment]
Any news about this merge?

**Comment by luismiguelprs** [comment]
> Any news about this merge?

Waiting here too!

**Comment by riccardomessineo** [comment]
This PR seems really straightforward but the reviewer seems inactive: latest activity is dated the 13th of November.

@acerix any news?

**Comment by dzmitrysoft** [comment]
@acerix , any news? Thanks

**Comment by arshaw** [comment]
sorry for the delay everyone. i will be merging this today and hopefully release tomorrow

**Comment by arshaw** [comment]
Released in v5.5.0: https://github.com/fullcalendar/fullcalendar-angular/issues/351#issuecomment-748538050

**Pull request merged**
