### PR TITLE
Update to angular 12.1.4

### PR DESCRIPTION
**Pull request by m0cs**

### CODE REVIEW

**Comment by m0cs** [comment]
Pending e2e tests #368

**Comment by arshaw** [comment]
Thank you so much for doing this. I will be gone on vacation for 2 weeks, but when I get back I will merge.

Just to be clear: this PR updates the dev repo to be Angular 12, but the current distributable version of the `@fullcalendar/angular` package works fine right?

**Comment by m0cs** [comment]
Yes!

**Comment by m0cs** [comment]
Maybe it's best to make an angular 12 branch, from master. And this pr point to that? Current dev branch is a little older, right?

**Comment by arshaw** [comment]
Did you use the `dev` branch as the base of your PR? It doesn't look like it, it look like you made it off of `master` . The `dev` branch is very very old. I plan to delete it. Please base everything off `master` if it isn't already.

**Comment by m0cs** [comment]
I `master` as base branch.

**Comment by arshaw** [comment]
Ok perfect. All good

**Comment by arshaw** [comment]
I was attempting to merge this while cutting a new fullcalendar release, but I'm getting these errors while building and running tests:

```
Generating browser application bundles (phase: setup)...    Project is attempting to disable the Ivy compiler. Angular versions 12 and higher do not support the deprecated View Engine compiler for applications. The Ivy compiler will be used to build this project.
    For additional information or if the build fails, please see https://angular.io/guide/ivy
```

and more

```
Generating browser application bundles (phase: building)...28 07 2021 08:41:38.537:INFO [karma-server]: Karma v6.3.4 server started at http://localhost:9876/
28 07 2021 08:41:38.539:INFO [launcher]: Launching browsers ChromeHeadless with concurrency unlimited
28 07 2021 08:41:38.542:INFO [launcher]: Starting browser ChromeHeadless
⠴ Generating browser application bundles (phase: building)...28 07 2021 08:47:11.232:WARN [launcher]: ChromeHeadless have not captured in 60000 ms, killing.
⠧ Generating browser application bundles (phase: building)...28 07 2021 08:47:11.676:INFO [launcher]: Trying to start ChromeHeadless again (1/2).
⠦ Generating browser application bundles (phase: building)...28 07 2021 08:47:16.362:ERROR [karma-server]: UnhandledRejection: Error: adjust-sourcemap-loader:
  For resource: /Users/adam/Projects/fullcalendar/packages-contrib/angular/projects/fullcalendar/src/lib/fullcalendar.component.scss
  Encoding with codec: projectRelative
  Absolute source: /Users/adam/Projects/fullcalendar/packages-premium/bundle/main.css
  Error: Qualified path resolution failed - none of the candidates can be found on the disk.
  Source path: /Users/adam/Projects/fullcalendar/packages-contrib/angular/node_modules/acorn/package.json
  Rejected candidate: /Users/adam/Projects/fullcalendar/packages-contrib/angular/node_modules/acorn/package.json
  Rejected candidate: /Users/adam/Projects/fullcalendar/packages-contrib/angular/node_modules/acorn/package.json.js
  Rejected candidate: /Users/adam/Projects/fullcalendar/packages-contrib/angular/node_modules/acorn/package.json.json
  Rejected candidate: /Users/adam/Projects/fullcalendar/packages-contrib/angular/node_modules/acorn/package.json.node
...
```

and more

```
28 07 2021 08:47:16.363:ERROR [karma-server]: Error: adjust-sourcemap-loader:
  For resource: /Users/adam/Projects/fullcalendar/packages-contrib/angular/projects/fullcalendar/src/lib/fullcalendar.component.scss
  Encoding with codec: projectRelative
  Absolute source: /Users/adam/Projects/fullcalendar/packages-premium/bundle/main.css
  Error: Qualified path resolution failed - none of the candidates can be found on the disk.
  Source path: /Users/adam/Projects/fullcalendar/packages-contrib/angular/node_modules/acorn/package.json
  Rejected candidate: /Users/adam/Projects/fullcalendar/packages-contrib/angular/node_modules/acorn/package.json
  Rejected candidate: /Users/adam/Projects/fullcalendar/packages-contrib/angular/node_modules/acorn/package.json.js
  Rejected candidate: /Users/adam/Projects/fullcalendar/packages-contrib/angular/node_modules/acorn/package.json.json
  Rejected candidate: /Users/adam/Projects/fullcalendar/packages-contrib/angular/node_modules/acorn/package.json.node
...
```

I will resume merging this at a later date after finishing the current release. @m0cs , if anything looks suspicious, let me know!

**Comment by m0cs** [comment]
> I was attempting to merge this while cutting a new fullcalendar release, but I'm getting these errors while building and running tests:
> 
> ```
> Generating browser application bundles (phase: setup)...    Project is attempting to disable the Ivy compiler. Angular versions 12 and higher do not support the deprecated View Engine compiler for applications. The Ivy compiler will be used to build this project.
>     For additional information or if the build fails, please see https://angular.io/guide/ivy
> ```
> 
> and more
> 
> ```
> Generating browser application bundles (phase: building)...28 07 2021 08:41:38.537:INFO [karma-server]: Karma v6.3.4 server started at http://localhost:9876/
> 28 07 2021 08:41:38.539:INFO [launcher]: Launching browsers ChromeHeadless with concurrency unlimited
> 28 07 2021 08:41:38.542:INFO [launcher]: Starting browser ChromeHeadless
> ⠴ Generating browser application bundles (phase: building)...28 07 2021 08:47:11.232:WARN [launcher]: ChromeHeadless have not captured in 60000 ms, killing.
> ⠧ Generating browser application bundles (phase: building)...28 07 2021 08:47:11.676:INFO [launcher]: Trying to start ChromeHeadless again (1/2).
> ⠦ Generating browser application bundles (phase: building)...28 07 2021 08:47:16.362:ERROR [karma-server]: UnhandledRejection: Error: adjust-sourcemap-loader:
>   For resource: /Users/adam/Projects/fullcalendar/packages-contrib/angular/projects/fullcalendar/src/lib/fullcalendar.component.scss
>   Encoding with codec: projectRelative
>   Absolute source: /Users/adam/Projects/fullcalendar/packages-premium/bundle/main.css
>   Error: Qualified path resolution failed - none of the candidates can be found on the disk.
>   Source path: /Users/adam/Projects/fullcalendar/packages-contrib/angular/node_modules/acorn/package.json
>   Rejected candidate: /Users/adam/Projects/fullcalendar/packages-contrib/angular/node_modules/acorn/package.json
>   Rejected candidate: /Users/adam/Projects/fullcalendar/packages-contrib/angular/node_modules/acorn/package.json.js
>   Rejected candidate: /Users/adam/Projects/fullcalendar/packages-contrib/angular/node_modules/acorn/package.json.json
>   Rejected candidate: /Users/adam/Projects/fullcalendar/packages-contrib/angular/node_modules/acorn/package.json.node
> ...
> ```
> 
> and more
> 
> ```
> 28 07 2021 08:47:16.363:ERROR [karma-server]: Error: adjust-sourcemap-loader:
>   For resource: /Users/adam/Projects/fullcalendar/packages-contrib/angular/projects/fullcalendar/src/lib/fullcalendar.component.scss
>   Encoding with codec: projectRelative
>   Absolute source: /Users/adam/Projects/fullcalendar/packages-premium/bundle/main.css
>   Error: Qualified path resolution failed - none of the candidates can be found on the disk.
>   Source path: /Users/adam/Projects/fullcalendar/packages-contrib/angular/node_modules/acorn/package.json
>   Rejected candidate: /Users/adam/Projects/fullcalendar/packages-contrib/angular/node_modules/acorn/package.json
>   Rejected candidate: /Users/adam/Projects/fullcalendar/packages-contrib/angular/node_modules/acorn/package.json.js
>   Rejected candidate: /Users/adam/Projects/fullcalendar/packages-contrib/angular/node_modules/acorn/package.json.json
>   Rejected candidate: /Users/adam/Projects/fullcalendar/packages-contrib/angular/node_modules/acorn/package.json.node
> ...
> ```
> 
> I will resume merging this at a later date after finishing the current release. @m0cs , if anything looks suspicious, let me know!

I'll take a look.

**Comment by m0cs** [comment]
@arshaw what tests did you run? `e2e` or `test` script?

**Comment by arshaw** [comment]
@m0cs , the problem only happens in fullcalendar's monorepo environment. When the fullcalendar-angular is cloned on its own, and I checkout your PR, everything works fine. The problem is on my end. I will look into it. Sorry about the false alarm.

**Comment by m0cs** [comment]
Don't worry, i take advantage of the shot, and update to latest angular core and fix lint task broken on the migration to eslint.

**Comment by arshaw** [comment]
The v6 codebase has been updated to angular 13, which outputs for angular 12 and up

**Pull request closed without merging**
