### PR TITLE
navLinkWeekClick as output

### PR DESCRIPTION
**Pull request by majky14**

### CODE REVIEW

**Comment by irustm** [comment]
Thanks!

**Comment by vmcbaptista** [comment]
Hi. When do you plan to release this fix? Thanks.

**Comment by irustm** [comment]
@arshaw ?

**Comment by arshaw** [comment]
hi @irustm , i'll make a new release early next week. could you let me know if there are any other fixes you've already merged into master?

**Comment by irustm** [comment]
only #241

**Comment by arshaw** [comment]
https://github.com/fullcalendar/fullcalendar-angular/releases/tag/v4.4.0

**Pull request merged**
