### PR TITLE
Upgrade package libs & angular 8

### PR DESCRIPTION
**Pull request by josemadev**

### CODE REVIEW

**Comment by irustm** [comment]
@josemadev thank to your PR

@arshaw I think it's time to upgrade.

----

This week I'm going to try to answer all the issues at the repository.

**Comment by josemadev** [comment]
Thanks @irustm for your attention

**Comment by micobarac** [comment]
`yarn add fullcalendar/fullcalendar-angular#pull/269/head` in Angular 9 gives me this error:

```
ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve '@fullcalendar/angular' in '/angular9/src/app'
```

**Comment by micobarac** [comment]
How do I add this pull request dependency using yarn?

**Comment by josemadev** [comment]
@micobarac yarn add https://github.com/josemadev/fullcalendar-angular#c12c0753f0ce354f29ea8db1a3cc2a871bca380e

**Comment by codewoot** [comment]
Still getting these errors:

ERROR in The target entry-point "@fullcalendar/angular" has missing dependencies:
 - @fullcalendar/core/types/input-types
 - @fullcalendar/core/datelib/env
 - @fullcalendar/core/datelib/duration
 - @fullcalendar/core/datelib/formatting
 - @fullcalendar/core/datelib/date-range
 - @fullcalendar/core/datelib/locale
 - @fullcalendar/core/validation
 - @fullcalendar/core/structs/event-source

package.json:
    "@angular/core": "^9.0.0-rc.14",
    "@fullcalendar/angular": "^4.3.1",
    "@fullcalendar/core": "^4.3.1",
    "@fullcalendar/daygrid": "^4.3.0",

**Comment by irustm** [comment]
@codewoot waiting #275

**Comment by arshaw** [comment]
https://github.com/fullcalendar/fullcalendar-angular/releases/tag/v4.4.0

**Pull request merged**
